# Generated by Django 3.1.5 on 2021-02-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0002_auto_20210202_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_completed',
            new_name='datecompleted',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='is_imp',
            new_name='important',
        ),
    ]
